M48
; DRILL file {KiCad 6.0.10-86aedd382b~118~ubuntu22.10.1} date Wed 01 Feb 2023 10:33:26 PM PST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-01T22:33:26-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.10-86aedd382b~118~ubuntu22.10.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X4.32Y-1.41
X4.34Y-2.91
X5.92Y-2.9
X5.9251Y-1.41
T0
M30
